VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Define web01 - Ubuntu 20.04
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.101"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # Define web02 - Ubuntu 20.04
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.102"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

 

  # Define db01 - CentOS 7
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"  # CentOS 7
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.103"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    # Provisioning to get hostname
    db01.vm.provision "shell", inline: <<-SHELL
       yum install wget unzip zip vim mariadb-server -y
       systemctl start mariadb
       systemctl enable mariadb
      echo "Hostname is: $(hostname)"
    SHELL
  end

    # Define web03 - Ubuntu 20.04
    config.vm.define "web03" do |web03|
      web03.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
      web03.vm.hostname = "web03"
      web03.vm.network "private_network", ip: "192.168.56.104"
      web03.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
    end

end
